# Generated by Django 3.0.6 on 2020-05-22 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affinity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('force', 'Force'), ('magic', 'Magic'), ('spirit', 'Spirit'), ('void', 'Void')], max_length=6, unique=True)),
                ('strength', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='strong_against', to='champion_helper.Affinity')),
                ('weakness', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weak_against', to='champion_helper.Affinity')),
            ],
        ),
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('telerians', 'Telerians'), ('gaellen_pact', 'Gaellen Pact'), ('corrupted', 'The Corrupted'), ('nyresan_union', 'Nyresan Union')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rarity', models.CharField(choices=[('c', 'Common'), ('unc', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legend', 'Legendary')], max_length=6)),
                ('type', models.CharField(choices=[('attack', 'Attack'), ('defense', 'Defense'), ('hp', 'HP'), ('support', 'Support')], max_length=7)),
                ('affinity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='champion_helper.Affinity')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('general', 'General'), ('dungeons', 'Character Dungeons'), ('keeps', 'Affinity Keeps')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(choices=[(0.0, 0.0), (0.1, 0.1), (0.2, 0.2), (0.3, 0.3), (0.4, 0.4), (0.5, 0.5), (0.6, 0.6), (0.7, 0.7), (0.8, 0.8), (0.9, 0.9), (1.0, 1.0), (1.1, 1.1), (1.2, 1.2), (1.3, 1.3), (1.4, 1.4), (1.5, 1.5), (1.6, 1.6), (1.7, 1.7), (1.8, 1.8), (1.9, 1.9), (2.0, 2.0), (2.1, 2.1), (2.2, 2.2), (2.3, 2.3), (2.4, 2.4), (2.5, 2.5), (2.6, 2.6), (2.7, 2.7), (2.8, 2.8), (2.9, 2.9), (3.0, 3.0), (3.1, 3.1), (3.2, 3.2), (3.3, 3.3), (3.4, 3.4), (3.5, 3.5), (3.6, 3.6), (3.7, 3.7), (3.8, 3.8), (3.9, 3.9), (4.0, 4.0), (4.1, 4.1), (4.2, 4.2), (4.3, 4.3), (4.4, 4.4), (4.5, 4.5), (4.6, 4.6), (4.7, 4.7), (4.8, 4.8), (4.9, 4.9), (5.0, 5.0)], decimal_places=1, max_digits=2)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champion_helper.Champion')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champion_helper.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('banner_lords', 'Banner Lords'), ('high_elves', 'High Elves'), ('sacred_order', 'The Sacred Order'), ('barbarians', 'Barbarians'), ('ogryn_tribes', 'Ogryn Tribes'), ('lizardmen', 'Lizardmen'), ('skinwalkers', 'Skinwalkers'), ('orcs', 'Orcs'), ('demonspawn', 'Demonspawn'), ('undead_hordes', 'Undead Hordes'), ('dark_elves', 'Dark Elves'), ('knight_revenant', 'Knight Revenant'), ('dwarves', 'Dwarves')], max_length=50, unique=True)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='champion_helper.Alliance')),
            ],
        ),
        migrations.AddField(
            model_name='champion',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='champion_helper.Faction'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('champion', 'location'), name='unique_champion_location_pair'),
        ),
        migrations.AddConstraint(
            model_name='faction',
            constraint=models.UniqueConstraint(fields=('name', 'alliance'), name='unique_faction_alliance_pair'),
        ),
        migrations.AddConstraint(
            model_name='affinity',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('strength__isnull', True), ('weakness__isnull', True)), models.Q(('strength__isnull', False), ('weakness__isnull', False), models.Q(_negated=True, strength_id=django.db.models.expressions.F('weakness'))), _connector='OR'), name='strength_weakness_are_both_null_or_populated_and_diff'),
        ),
        migrations.AddConstraint(
            model_name='affinity',
            constraint=models.UniqueConstraint(fields=('strength', 'weakness'), name='unique_strength_weakness_pair'),
        ),
    ]
