# Generated by Django 3.0.6 on 2020-05-19 03:17

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affinity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('force', 'Force'), ('magic', 'Magic'), ('spirit', 'Spirit'), ('void', 'Void')], max_length=6, unique=True)),
                ('strength', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='strong_against', to='champion_helper.Affinity')),
                ('weakness', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weak_against', to='champion_helper.Affinity')),
            ],
        ),
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('telarians', 'Telarians'), ('gaellen_pact', 'Gaellen Pact'), ('corrupted', 'The Corrupted'), ('nyresan_union', 'Nyresan Union')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rarity', models.CharField(choices=[('c', 'Common'), ('unc', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legend', 'Legendary')], max_length=6)),
                ('type', models.CharField(choices=[('attack', 'Attack'), ('defense', 'Defense'), ('hp', 'HP'), ('support', 'Support')], max_length=7)),
                ('affinity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='champion_helper.Affinity')),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_locations', models.DecimalField(decimal_places=1, max_digits=2)),
                ('arena_offense', models.DecimalField(decimal_places=1, max_digits=2)),
                ('arena_defense', models.DecimalField(decimal_places=1, max_digits=2)),
                ('clan_boss', models.DecimalField(decimal_places=1, max_digits=2)),
                ('faction_wars', models.DecimalField(decimal_places=1, max_digits=2)),
                ('ice_golem', models.DecimalField(decimal_places=1, max_digits=2)),
                ('dragon', models.DecimalField(decimal_places=1, max_digits=2)),
                ('minotaur', models.DecimalField(decimal_places=1, max_digits=2)),
                ('fire_knight', models.DecimalField(decimal_places=1, max_digits=2)),
                ('spider', models.DecimalField(decimal_places=1, max_digits=2)),
                ('void_arcane', models.DecimalField(decimal_places=1, max_digits=2)),
                ('force', models.DecimalField(decimal_places=1, max_digits=2)),
                ('magic', models.DecimalField(decimal_places=1, max_digits=2)),
                ('spirit', models.DecimalField(decimal_places=1, max_digits=2)),
                ('champion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='champion_helper.Champion')),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='champion_helper.Alliance')),
            ],
        ),
        migrations.AddField(
            model_name='champion',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='champion_helper.Faction'),
        ),
        migrations.AddConstraint(
            model_name='faction',
            constraint=models.UniqueConstraint(fields=('name', 'alliance'), name='unique_faction_alliance_pair'),
        ),
        migrations.AddConstraint(
            model_name='affinity',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('strength__isnull', True), ('weakness__isnull', True)), models.Q(('strength__isnull', False), ('weakness__isnull', False), models.Q(_negated=True, strength_id=django.db.models.expressions.F('weakness'))), _connector='OR'), name='strength_weakness_are_both_null_or_populated_and_diff'),
        ),
        migrations.AddConstraint(
            model_name='affinity',
            constraint=models.UniqueConstraint(fields=('strength', 'weakness'), name='unique_strength_weakness_pair'),
        ),
    ]
