# Generated by Django 3.0.6 on 2020-05-23 22:56

from django.db import migrations


def load_champions(apps, schema_editor):
    # TODO: Write logic to read data from file and write to DB
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('champion_helper', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_champions)
    ]
