# Generated by Django 3.0.6 on 2020-05-20 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('champion_helper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
        migrations.AlterField(
            model_name='affinity',
            name='strength',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='strong_against', to='champion_helper.Affinity'),
        ),
        migrations.AlterField(
            model_name='affinity',
            name='weakness',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weak_against', to='champion_helper.Affinity'),
        ),
        migrations.AlterField(
            model_name='alliance',
            name='name',
            field=models.CharField(choices=[('telerians', 'Telerians'), ('gaellen_pact', 'Gaellen Pact'), ('corrupted', 'The Corrupted'), ('nyresan_union', 'Nyresan Union')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='faction',
            name='name',
            field=models.CharField(choices=[('banner_lords', 'Banner Lords'), ('high_elves', 'High Elves'), ('sacred_order', 'The Sacred Order'), ('barbarians', 'Barbarians'), ('ogryn_tribes', 'Ogryn Tribes'), ('lizardmen', 'Lizardmen'), ('skinwalkers', 'Skinwalkers'), ('orcs', 'Orcs'), ('demonspawn', 'Demonspawn'), ('undead_hordes', 'Undead Hordes'), ('dark_elves', 'Dark Elves'), ('knight_revenant', 'Knight Revenant'), ('dwarves', 'Dwarves')], max_length=50, unique=True),
        ),
    ]
