# Generated by Django 3.0.6 on 2020-05-26 21:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champion_helper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.DecimalField(choices=[(Decimal('0'), Decimal('0')), (Decimal('0.1'), Decimal('0.1')), (Decimal('0.2'), Decimal('0.2')), (Decimal('0.3'), Decimal('0.3')), (Decimal('0.4'), Decimal('0.4')), (Decimal('0.5'), Decimal('0.5')), (Decimal('0.6'), Decimal('0.6')), (Decimal('0.7'), Decimal('0.7')), (Decimal('0.8'), Decimal('0.8')), (Decimal('0.9'), Decimal('0.9')), (Decimal('1'), Decimal('1')), (Decimal('1.1'), Decimal('1.1')), (Decimal('1.2'), Decimal('1.2')), (Decimal('1.3'), Decimal('1.3')), (Decimal('1.4'), Decimal('1.4')), (Decimal('1.5'), Decimal('1.5')), (Decimal('1.6'), Decimal('1.6')), (Decimal('1.7'), Decimal('1.7')), (Decimal('1.8'), Decimal('1.8')), (Decimal('1.9'), Decimal('1.9')), (Decimal('2'), Decimal('2')), (Decimal('2.1'), Decimal('2.1')), (Decimal('2.2'), Decimal('2.2')), (Decimal('2.3'), Decimal('2.3')), (Decimal('2.4'), Decimal('2.4')), (Decimal('2.5'), Decimal('2.5')), (Decimal('2.6'), Decimal('2.6')), (Decimal('2.7'), Decimal('2.7')), (Decimal('2.8'), Decimal('2.8')), (Decimal('2.9'), Decimal('2.9')), (Decimal('3'), Decimal('3')), (Decimal('3.1'), Decimal('3.1')), (Decimal('3.2'), Decimal('3.2')), (Decimal('3.3'), Decimal('3.3')), (Decimal('3.4'), Decimal('3.4')), (Decimal('3.5'), Decimal('3.5')), (Decimal('3.6'), Decimal('3.6')), (Decimal('3.7'), Decimal('3.7')), (Decimal('3.8'), Decimal('3.8')), (Decimal('3.9'), Decimal('3.9')), (Decimal('4'), Decimal('4')), (Decimal('4.1'), Decimal('4.1')), (Decimal('4.2'), Decimal('4.2')), (Decimal('4.3'), Decimal('4.3')), (Decimal('4.4'), Decimal('4.4')), (Decimal('4.5'), Decimal('4.5')), (Decimal('4.6'), Decimal('4.6')), (Decimal('4.7'), Decimal('4.7')), (Decimal('4.8'), Decimal('4.8')), (Decimal('4.9'), Decimal('4.9')), (Decimal('5'), Decimal('5'))], decimal_places=1, max_digits=2),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(check=models.Q(('value__gte', 0.0), ('value__lte', 5.0)), name='zero_to_five_rating'),
        ),
    ]
