# Generated by Django 3.0.6 on 2020-05-23 22:56

from django.db import migrations

import csv
import os
from decimal import Decimal

from raid.settings import DATA_DIR


def get_key_by_value(dictionary, val):
    """
    Finds the key of a given value in the specified
    dictionary.
    """
    for key, value in dictionary.items():
        if val == value:
            return key
    raise ValueError(f"Value({val}) not found")


def load_champions(apps, schema_editor):
    """
    Iterates over the rows in the Rai
    """
    Champions = apps.get_model("champion_helper", "Champion")
    Ratings = apps.get_model("champion_helper", "Rating")
    Factions = apps.get_model("champion_helper", "Faction")
    Locations = apps.get_model("champion_helper", "Location")
    Affinities = apps.get_model("champion_helper", "Affiinity")

    AFFINITIES = dict(Affinities.AFFINITIES)
    CHAMP_RARITIES = dict(Champions.RARITIES)
    CHAMP_TYPES = dict(Champions.TYPES)
    FACTIONS = dict(Factions.FACTIONS)
    POSSIBLE_RATINGS = dict(Ratings.POSSIBLE_RATINGS)

    data_file = os.path.join(DATA_DIR, "Raid_Shadow_Legends_Champions.csv")
    with open(data_file, newline="") as initial_champs:
        reader = csv.DictReader(initial_champs)
        for row in reader:
            champ_name = row["Champion"]
            champ_type = row["Type"]
            champ_faction = row["Faction"]
            champ_rarity = row["Rarity"]
            champ_affinity = row["Affinity"]
            
            new_champ = Champions.objects.get_or_create(
                name=champ_name,
                type=get_key_by_value(CHAMP_TYPES, champ_type),
                affinity=Affinities.objects.get(
                    name=get_key_by_value(AFFINITIES, champ_affinity)
                ),
                faction=Factions.objects.get(
                    name=get_key_by_value(FACTIONS, champ_faction)
                ),
                rarity=get_key_by_value(
                    CHAMP_RARITIES, champ_rarity
                )
            )
            new_champ.save()
            new_champ.refresh_from_db()
            # For each in-game location, add
            # the rating from the csv for the
            # champ being added
            for location in Locations.objects.all():
                rating = Decimal(row[str(location)])
                new_rating = Ratings.objects.get_or_create(
                    champion=new_champ,
                    location=location,
                    value=get_key_by_value(
                        POSSIBLE_RATINGS, rating
                    )
                )
                new_rating.save()


class Migration(migrations.Migration):

    dependencies = [
        ("champion_helper", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_champions)
    ]
