# Generated by Django 3.0.6 on 2020-06-10 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champion_helper', '0004_auto_20200528_1737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['location', '-value']},
        ),
    ]
