# Generated by Django 3.0.6 on 2020-07-13 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('champion_helper', '0005_auto_20200609_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChampion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='champion_helper.Champion')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
