# Generated by Django 3.0.6 on 2020-07-29 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('champion_helper', '0006_userchampion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserChampion',
        ),
    ]
